version: "3.8"

services:
  postgres:
    container_name: udri-plus-db
    image: postgres:latest
    ports:
      - "${DB_PORT}:5432"
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PWD}
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
